# Form implementation generated from reading ui file 'dialog_register.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 382)
        Dialog.setStyleSheet("background: #00BFFF")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 310, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.buttonBox.setFont(font)
        self.buttonBox.setStyleSheet("color: white;")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 180, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 2px solid;\n"
"border-color:white;\n"
"border-radius: 25;\n"
"color: white")
        self.label.setObjectName("label")
        self.cirID = QtWidgets.QLineEdit(parent=Dialog)
        self.cirID.setGeometry(QtCore.QRect(10, 30, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Apple Symbols")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cirID.setFont(font)
        self.cirID.setStyleSheet("background-color: #00BFFF;\n"
"color: white;\n"
"font: 30pt \"Apple Symbols\";\n"
"border: 2px solid white;\n"
"border-radius: 30;")
        self.cirID.setFrame(False)
        self.cirID.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cirID.setObjectName("cirID")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 381, 61))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #00BFFF;\n"
"    background-color: white;\n"
"    border: 2px solid rgb(59, 131, 189);\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(200, 255, 255);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Регистрация"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.cirID.setPlaceholderText(_translate("Dialog", "%cirID%"))
        self.pushButton.setText(_translate("Dialog", "ПОИСК"))
